version: 2
updates:
  - package-ecosystem: "npm" # detecta pnpm-lock.yaml automáticamente
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      typescript:
        patterns: ["typescript", "@types/*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      github-actions:
        patterns: ["*"]
